workflows:
  expo_android_apk:
    name: Expo Android APK
    max_build_duration: 60
    instance_type: linux_x1

    environment:
      node: 18.18.2
      npm: 9.8.1
      vars:
        # No pongas el valor aquí, lo agregarás en Codemagic como variable segura
        EXPO_TOKEN: En_Codemagic

    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/.cache/eas
        - $HOME/.cache/expo

    scripts:
      - name: Instalar dependencias
        script: npm ci

      - name: Instalar EAS CLI
        script: npm i -g eas-cli

      - name: Autenticarse en Expo (con token)
        script: |
          # Si ya estás autenticado, whoami no falla; si no, login con token
          eas whoami || eas account:login --token "$EXPO_TOKEN"

      - name: Compilar APK con EAS (perfil "preview")
        script: |
          # Debes tener un eas.json con el perfil 'preview' y buildType=apk
          eas build -p android --profile preview --non-interactive --wait

      - name: Descargar el artefacto (APK) y guardarlo para Codemagic
        script: |
          # Descarga el último build de Android y lo guarda como build.apk
          eas build:download --platform android --latest --path build.apk
          ls -lh build.apk

    artifacts:
      - build.apk
