workflows:
  expo_android_apk:
    name: Expo Android APK
    max_build_duration: 60
    instance_type: linux

    environment:
      node: 18.18.2
      npm: 9.8.1
      groups:
        - En_Codemagic   # <-- el grupo que creaste con EXPO_TOKEN

    cache:
      cache_paths:
        - $HOME/.npm
        - $HOME/.cache/eas

    scripts:
      - name: Instalar dependencias
        script: npm ci

      - name: Instalar EAS CLI
        script: npm i -g eas-cli

      # Si no tienes definido el perfil "apk", creamos un eas.json mínimo
      - name: Asegurar perfil APK en eas.json
        script: |
          if [ ! -f eas.json ]; then
            cat > eas.json <<'JSON'
            {
              "build": {
                "apk": {
                  "android": { "buildType": "apk" }
                }
              }
            }
            JSON
          fi

      # EAS usa EXPO_TOKEN desde el entorno (lo inyecta Codemagic por el grupo)
      - name: Lanzar build APK en Expo (EAS cloud)
        script: |
          set -e
          eas build -p android --profile apk --non-interactive --json > build.json
          echo "Build JSON:"
          cat build.json

          # Extraer la URL de la página del build y luego la URL del artefacto
          BUILD_ID=$(node -e "console.log(require('./build.json')[0].id)")
          echo "BUILD_ID=$BUILD_ID"

          # Obtener info del build para leer el artifact URL
          eas build:view $BUILD_ID --json > build_info.json
          ARTIFACT_URL=$(node -e "console.log(require('./build_info.json').artifacts?.buildUrl || '')")

          echo "Artifact URL: $ARTIFACT_URL"

          mkdir -p artifacts
          if [ -n "$ARTIFACT_URL" ]; then
            curl -L "$ARTIFACT_URL" -o artifacts/app.apk
          else
            echo "No se pudo obtener la URL del APK."
            exit 1
          fi

    artifacts:
      - artifacts/*.apk
